from django.test import TestCase
from operations.models import Course 
# Create your tests here.

class CourseTestCase(TestCase):
    def setUp(self):
        Course.objects.create(name="Big Data",
                              desc="Some course description",
                              link="Some link",
                              testimonial="some testimonial",
                              active=True)
        
    def test_courses_is_not_empty(self):
        """There is at least one course in the database"""
        self.assertGreater(Course.objects.count(), 0)
        self.assertEqual(1, Course.objects.count())

    def test_slugs_is_auto_generated(self):
        '''Slugs are autogenerated for the models'''
        self.assertIsNotNone(u"", Course.objects.first().slug)
        self.assertNotEqual(u"", Course.objects.first().slug)